### ISSUE TITLE
Requested new locales

### ISSUE THREAD

**Issue by marwahaha** [moment/moment#4949]
## These locales have been requested. Please add them if you can!
- [x] en-sg https://github.com/moment/moment/issues/4791 (see https://github.com/moment/moment/pull/4951)
- [x] zh-mo https://github.com/moment/moment/issues/4827 (see https://github.com/moment/moment/pull/5172)
- [x] en-in https://github.com/moment/moment/issues/4012 (see https://github.com/moment/moment/pull/4626)
- [ ] ti https://github.com/moment/moment/issues/5438
- [ ] east kurdish https://github.com/moment/moment/issues/4970 (may be challenging; based on solar calendar)
- [ ]  [locale] bo: Add bo-IN locale and align bo with CLDR #4369 
## How to add a new locale:
* Verify the ISO 639 code.
* Copy the `src/locale/en-gb.js` file or similar into `src/locale/<XX>.js` and update for the new language. 
* Copy the `src/test/locale/en-gb.js` file or similar into `src/test/locale/<XX>.js` and update for the new locale.
* Go to the command line, navigate to this project, and run grunt. All the tests should pass.
* Make a pull request!

## Requesting a new locale
comment on this issue, and i can add it to the main issue text.

**Comment by M-C-Yates** [comment]
Is it alright if I do this?

**Comment by gorkemuz** [comment]
I can add Turkish if you need.

**Comment by ABhakuni** [comment]
Is this resolved? If not, I would like to take it

**Comment by mantinone** [comment]
I think this one can be marked as closed?  It looks like all of the linked issues have had pull requests and been closed.

**Comment by bukkysos** [comment]
Missing support for ng-igbo

**Comment by bukkysos** [comment]
Created a new locale (Igbo language, Nigeria). Test has been throwing error: "
**Actual value:
2 02 2nd
Expected value:
1 01 1st


Warning: 199 tests failed Use --force to continue.

Aborted due to warnings.**
"
Need help. Anyone, please??

**Comment by Krinkle** [comment]
It might be better to invest in supporting CLDR and/or native `Intl` so that you get these, and a few hundred more languages, for free bascially.

Either by consuming CLDR upstream data directly, or throuhh the [cldr.js](https://github.com/rxaviers/cldrjs) package that spun out of Globalize (ref https://github.com/moment/moment/issues/1241).

**Comment by maxammann** [comment]
Sounds like a good idea. CLDR also supports Tigrinia. To check for support download core.zip here: https://unicode.org/Public/cldr/37/

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/
